---

plugins:
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - fluent-plugin-http-client.gemspec
    - test/**/*.rb

Metrics/ClassLength:
  Max: 150
  Exclude:
    - test/**/*.rb

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false
